reader:
  nsog:
    data_dir: '{repo_path}/notebooks/NSOG_notebooks/data'
    detections_csv: otn_detections_2018-2020_range_test_detections.csv
    vendor_tag_specs: nsog_tags.xlsx
data:
  sources:
    load_wavedir: 'era5'
    load_waveheight: 'era5'
    load_waveperiod: 'era5'
    load_wind_uv: 'era5'
    load_wind_u: 'era5'
    load_wind_v: 'era5'
bounds:
  description: Northern Straight of Georgia (NSOG)
  start: 2018-01-01
  end: 2019-04-15
  lat_center: 49.7231
  lon_center: -124.6858
  n_offset: 0.3
  s_offset: 0.3
  e_offset: 0.3
  w_offset: 0.4
