name: range-driver
channels:
  - conda-forge
dependencies:
  # Base
  - python=3.8
  - jupyter
  - pip
  - setuptools
  # Data Prep
  - pandas>=1
  - numpy
  - scipy
  - geopy
  - xlrd
  - xarray
  # Plotting
  - matplotlib
  - seaborn
  - ipyleaflet
  - ipywidgets
  - pyproj
  # Modeling
  - scikit-learn
  - pip:
    - pyyaml
    - pandas_ods_reader
    - kadlu
    - streamlit
    - streamlit-folium
    - streamlit-ace
    - sphinx
    - sphinx-rtd-theme
  # Kadlu
  - cartopy
  - cdsapi
  - cython
  - geos
  - gsw
  - imageio
  - make
  - netCDF4
  - Pillow
  - Proj
  - pygrib
  - pytest



