name: learn-github-actions
on:
  push:
    branches: [ public ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python --version
