name: Sphinx Doc Build
on:
  push:
    branches: [ public ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sphinx-docs:
    name: Build sphinx docs on Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.8
          activate-environment: range-driver
          environment-file: environment.yml
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: Install range_driver
        run: |
          pip install -e .
      - name: Cache data
        id: cache-data
        uses: actions/cache@v2
        with:
          path: data.zip
          key: ${{ runner.os }}-data
      - name: Download data
        if: ${{ !env.ACT }} && {{steps.cache-data.outputs.cache-hit != 'true'}}
        uses: wei/wget@v1
        with:
          args: -O data.zip "https://vault.sfu.ca/index.php/s/GFlTJ9maTYjuMlP/download"
      - name: Organize data
        run: |
          unzip data.zip
      - name: Organize tutorial notebooks
        run: |
          python3 action_setup.py
          git clone https://github.com/sfu-bigdata/range-driver-tutorials.git
          mv range-driver-tutorials/tutorials/NSOG_Jan2018 docs/source/tutorials/
          mv range-driver-tutorials/tutorials/MahoneBay2016 docs/source/tutorials/
      - name: Build Sphinx docs
        run: | 
          cd docs
          pip install -r requirements.txt
          make github
      - name: Commit Documentation Changes
        run: | 
          git clone https://github.com/sfu-bigdata/range-driver.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages/
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore that.
      - name: Push changes
        if: ${{ !env.ACT }}
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
