name: Sphinx Doc Build
on:
  push:
    branches: [ public ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sphinx-docs:
    name: Build sphinx docs on Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: range-driver
          environment-file: environment.yml
          auto-activate-base: false        
      - name: Install range_driver
        run: | 
          pip install -e .
      - name: Build Sphinx docs
        run: | 
          cd docs
          pip install -r requirements.txt
          make html . _build
      - name: Commit Documentation Changes
        run: | 
          git clone https://github.com/sfu-bigdata/range-driver.git --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages-test
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
