name: Sphinx Doc Build
on:
  push:
    branches: [ public ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup Environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: range-driver
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false        
      - name: Install range_driver
        run: pip install -e .
      # Builds Sphinx Docs
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "echo $(pwd); which python; "
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      - name: Commit documentation changes
        run: |
          git clone https://github.com/sfu-bigdata/range-driver.git --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages-test
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
